user:
  username: your account
  password: your password
slot:
  room: the room
  seat: the seat
schedule:
  date: 2024/12/01
  start_time: '08:00:00'
  end_time: '22:00:00'
notifier:
  gmail: 
  # note: this is the application-specific password, not the Google password
  password: 
